### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26x0

### Add to the source dirs
CONTIKI_TARGET_DIRS += launchpad/cc2650 launchpad/cc2650/max30100

BOARD_SOURCEFILES += MAX30100.c

### Include the common launchpad makefile
include $(PLATFORM_ROOT_DIR)/launchpad/Makefile.launchpad
